spring:
  application:
    name: roomify

  datasource:
    url: ${DB_URL}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

aws:
  s3:
    access:
      key: ${AWS_S3_ACCESS_KEY}
    secret:
      key: ${AWS_S3_SECRET_KEY}
    bucket: ${AWS_S3_BUCKET_NAME}
  region: ${AWS_S3_REGION}

